# -*- coding: utf-8 -*-
"""AirQualityIndexPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hBckuBj184iUtg974HooZRbDUbOrmVm4
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt


from tensorflow import keras
from tensorflow.keras import layers
from keras_tuner.tuners import RandomSearch

#pip install -U keras-tuner

data=pd.read_csv('Real_Combine.csv')
data.head()

X=data.iloc[:,:-1]
y=data.iloc[:,-1]

print (X.head())
print (y.head())

def build_model(hp):
  model=keras.Sequential()
  for i in range(hp.Int('num_layers',2,5)):
    model.add(layers.Dense(units=hp.Int('units_'+str(i),min_value=2,max_value=10),
              activation='relu'))

  model.add(layers.Dense(1,activation='linear'))

  model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate',[1e-2])),
                loss='mean_absolute_error',metrics=['mean_absolute_error'])
  return model

tuner = RandomSearch(
    build_model,
    objective='val_mean_absolute_error',
    max_trials=2,
    )

tuner.search_space_summary()

X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0)

tuner.search(X_train,y_train,epochs=3,validation_data=(X_test,y_test))

tuner.results_summary()